/** 
 * @typedef {object} ExchangeRequest
 * @property {string} table
 * @property {rates} rates
 * @property {string} lastupdate
 */

/**
 * @typedef {object} rates
 * @property {number} AED
 * @property {number} AFN
 * @property {number} ALL
 * @property {number} AMD
 * @property {number} ANG
 * @property {number} AOA
 * @property {number} ARS
 * @property {number} AUD
 * @property {number} AWG
 * @property {number} AZN
 * @property {number} BAM
 * @property {number} BBD
 * @property {number} BDT
 * @property {number} BGN
 * @property {number} BHD
 * @property {number} BIF
 * @property {number} BMD
 * @property {number} BND
 * @property {number} BOB
 * @property {number} BRL
 * @property {number} BSD
 * @property {number} BTC
 * @property {number} BTN
 * @property {number} BTS
 * @property {number} BWP
 * @property {number} BYN
 * @property {number} BZD
 * @property {number} CAD
 * @property {number} CDF
 * @property {number} CHF
 * @property {number} CLF
 * @property {number} CLP
 * @property {number} CNH
 * @property {number} CNY
 * @property {number} COP
 * @property {number} CRC
 * @property {number} CUC
 * @property {number} CUP
 * @property {number} CVE
 * @property {number} CZK
 * @property {number} DASH
 * @property {number} DJF
 * @property {number} DKK
 * @property {number} DOGE
 * @property {number} DOP
 * @property {number} DZD
 * @property {number} EGP
 * @property {number} ERN
 * @property {number} ETB
 * @property {number} ETH
 * @property {number} EUR
 * @property {number} FJD
 * @property {number} FKP
 * @property {number} GBP
 * @property {number} GEL
 * @property {number} GGP
 * @property {number} GHS
 * @property {number} GIP
 * @property {number} GMD
 * @property {number} GNF
 * @property {number} GTQ
 * @property {number} GYD
 * @property {number} HKD
 * @property {number} HNL
 * @property {number} HRK
 * @property {number} HTG
 * @property {number} HUF
 * @property {number} IDR
 * @property {number} ILS
 * @property {number} IMP
 * @property {number} INR
 * @property {number} IQD
 * @property {number} IRR
 * @property {number} ISK
 * @property {number} JEP
 * @property {number} JMD
 * @property {number} JOD
 * @property {number} JPY
 * @property {number} KES
 * @property {number} KGS
 * @property {number} KHR
 * @property {number} KMF
 * @property {number} KPW
 * @property {number} KRW
 * @property {number} KWD
 * @property {number} KYD
 * @property {number} KZT
 * @property {number} LAK
 * @property {number} LBP
 * @property {number} LD
 * @property {number} LKR
 * @property {number} LRD
 * @property {number} LSL
 * @property {number} LTC
 * @property {number} LYD
 * @property {number} MAD
 * @property {number} MDL
 * @property {number} MGA
 * @property {number} MKD
 * @property {number} MMK
 * @property {number} MNT
 * @property {number} MOP
 * @property {number} MRO
 * @property {number} MRU
 * @property {number} MUR
 * @property {number} MVR
 * @property {number} MWK
 * @property {number} MXN
 * @property {number} MYR
 * @property {number} MZN
 * @property {number} NAD
 * @property {number} NGN
 * @property {number} NIO
 * @property {number} NOK
 * @property {number} NPR
 * @property {number} NXT
 * @property {number} NZD
 * @property {number} OMR
 * @property {number} PAB
 * @property {number} PEN
 * @property {number} PGK
 * @property {number} PHP
 * @property {number} PKR
 * @property {number} PLN
 * @property {number} PYG
 * @property {number} QAR
 * @property {number} RON
 * @property {number} RSD
 * @property {number} RUB
 * @property {number} RWF
 * @property {number} SAR
 * @property {number} SBD
 * @property {number} SCR
 * @property {number} SDG
 * @property {number} SEK
 * @property {number} SGD
 * @property {number} SHP
 * @property {number} SLL
 * @property {number} SOS
 * @property {number} SRD
 * @property {number} SSP
 * @property {number} STD
 * @property {number} STN
 * @property {number} STR
 * @property {number} SVC
 * @property {number} SYP
 * @property {number} SZL
 * @property {number} THB
 * @property {number} TJS
 * @property {number} TMT
 * @property {number} TND
 * @property {number} TOP
 * @property {number} TRY
 * @property {number} TTD
 * @property {number} TWD
 * @property {number} TZS
 * @property {number} UAH
 * @property {number} UGX
 * @property {number} USD
 * @property {number} UYU
 * @property {number} UZS
 * @property {number} VEF_BLKMKT
 * @property {number} VEF_DICOM
 * @property {number} VEF_DIPRO
 * @property {number} VES
 * @property {number} VND
 * @property {number} VUV
 * @property {number} WST
 * @property {number} XAF
 * @property {number} XAG
 * @property {number} XAU
 * @property {number} XCD
 * @property {number} XDR
 * @property {number} XMR
 * @property {number} XOF
 * @property {number} XPD
 * @property {number} XPF
 * @property {number} XPT
 * @property {number} XRP
 * @property {number} YER
 * @property {number} ZAR
 * @property {number} ZMW
 * @property {number} ZWL
 * @property {number} NMC
 * @property {number} PPC
 * @property {number} NVC
 * @property {number} XPM
 * @property {number} EAC
 * @property {number} VTC
 * @property {number} EMC
 * @property {number} FCT
 * @property {number} SLE
 * @property {number} XCG
 * @property {number} ZWG
 */